### ISSUE TITLE
 ChatGLM4Tokenizer._pad() got an unexpected keyword argument 'padding_side'

### ISSUE THREAD

**Issue by Vineshg** [Nojahhh/ComfyUI_GLM4_Wrapper#1] opened 2024-09-26 02:40 UTC
Getting following error in prompt enhance:
!!! Exception during processing !!! ChatGLM4Tokenizer._pad() got an unexpected keyword argument 'padding_side'

`Loading GLM-4 model: THUDM/glm-4v-9b
!!! Exception during processing !!! ChatGLM4Tokenizer._pad() got an unexpected keyword argument 'padding_side'
Traceback (most recent call last):
  File "D:\ws\dev\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ws\dev\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ws\dev\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ws\dev\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ws\dev\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GLM4_Wrapper\nodes.py", line 105, in enhance_prompt
    inputs = tokenizer.apply_chat_template(messages,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\praggie\.cache\huggingface\modules\transformers_modules\THUDM\glm-4v-9b\01328faefe122fe605c1c127b62e6031d3ffebf7\tokenization_chatglm.py", line 251, in apply_chat_template
    output = self.batch_encode_plus(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ws\dev\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3315, in batch_encode_plus
    return self._batch_encode_plus(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ws\dev\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils.py", line 889, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ws\dev\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils.py", line 967, in _batch_prepare_for_model
    batch_outputs = self.pad(
                    ^^^^^^^^^
  File "D:\ws\dev\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 3531, in pad
    outputs = self._pad(
              ^^^^^^^^^^
TypeError: ChatGLM4Tokenizer._pad() got an unexpected keyword argument 'padding_side'
`

**Comment by Nojahhh** [comment] 2024-09-26 06:04
Think this might be caused by dependency mismatch. What version of transformers do you use?

**Comment by Nojahhh** [comment] 2024-09-26 08:25
GLM-4 requires transformers>=4.44.0. You can update it by running the embedded python in ComfyUI folder.
`python_embeded/python -m pip install transformers==4.44.0`

**Comment by Nojahhh** [comment] 2024-10-01 18:54
Managed to recreate your issue with transformers 4.45.1.
Downgrading transformers to 4.44.0 solves it.

Closing this for now.

**Closed as completed by Nojahhh** 2024-10-01 18:54 UTC

**Comment by Nojahhh** [comment] 2024-10-01 19:14
Found a link describing this on their huggingface as well.
[HuggingFace THUDM glm-4v-9b Discussion #36](https://huggingface.co/THUDM/glm-4v-9b/discussions/36)
